project_id = "qnhrqipmkmipstzratjv"

[auth]
enabled = true
external_url = "https://qnhrqipmkmipstzratjv.supabase.co"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_anonymous_sign_ins = false

[auth.email]
enable_sign_up = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 5432
shadow_port = 54320
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[functions.send-form-email]
verify_jwt = false

[functions.extract-website-fields]
verify_jwt = false

[functions.extract-website-theme]
verify_jwt = false

[functions.extract-form-from-image]
verify_jwt = false

[functions.analyze-submissions]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false