// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnhrqipmkmipstzratjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuaHJxaXBta21pcHN0enJhdGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODE4NDIsImV4cCI6MjA2NjM1Nzg0Mn0.0QY3bc3BGfxcYjuyxroQ_oir2DKAurn4jTeUazsfDrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);